[[language]]
name = "rust"
rulers = [101]

[[language]]
name = "r"
language-servers = ["air"]
auto-format = true

[language-server.air]
command = "air"
args = ["language-server"]

[[language]]
name = "rmarkdown"
file-types = ["rmd", "Rmd", "qmd"]

[[language]]
name = "fish"
auto-format = false

[[language]]
name = "python"
auto-format = true
rulers = [101]
language-servers = [
    {name = "pyright"},
    {name = "ruff"},
]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
config = {}

[language-server.ruff]
command = "ruff"
args = ["server"]
config = {}

[[language]]
name = "nextflow"
scope = "source.nextflow"
file-types = ["nf"]
comment-token = "//"
